server:
 port: 8080
spring:
 application:
   name: room-service
 datasource:
   url: jdbc:mysql://localhost:3306/roomdb
   username: root
   password: root
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
